### ISSUE TITLE
error when running "!python -m supercharged.main spoonflower --use_list_range --limit 5 --save_csv"

### ISSUE THREAD

**Issue by HanyBoktor** [codingforentrepreneurs/Supercharged-Web-Scraping-with-Asyncio#8]
even installed latest chromedriver, but after running (!python -m supercharged.main spoonflower --use_list_range --limit 5 --save_csv) i got the following error

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hany\Desktop\Supercharged-Web-Scraping-with-Asyncio-master\supercharged\main.py", line 1, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
![error](https://user-images.githubusercontent.com/82240819/115094996-f0f01300-9f1f-11eb-8b1a-e995f04b68e6.JPG)

**Comment by codingforentrepreneurs** [comment]
```
pip install fire
```
> I'll add it to `requirements.txt` if it's not there already. 👍

**Comment by HanyBoktor** [comment]
after installed fire, i got bigger issue :(


Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hany\Desktop\Supercharged-Web-Scraping-with-Asyncio-master\supercharged\main.py", line 9, in <module>
    fire.Fire(Pipeline)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\ProgramData\Anaconda3\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\Hany\Desktop\Supercharged-Web-Scraping-with-Asyncio-master\supercharged\projects\spoonflower.py", line 145, in run_spoonflower
    results = asyncio.run(run(urls, start=start))
  File "C:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Hany\Desktop\Supercharged-Web-Scraping-with-Asyncio-master\supercharged\projects\spoonflower.py", line 107, in run
    list_of_links = await asyncio.gather(*results)
  File "C:\Users\Hany\Desktop\Supercharged-Web-Scraping-with-Asyncio-master\supercharged\projects\spoonflower.py", line 87, in spoonflower_scraper
    body = await scraper(url, i=i, timeout=timeout, start=start, body_delay=10)
  File "C:\Users\Hany\Desktop\Supercharged-Web-Scraping-with-Asyncio-master\supercharged\scrapers.py", line 9, in scraper
    async with get_session(service, browser) as session:
  File "C:\ProgramData\Anaconda3\lib\site-packages\arsenic\__init__.py", line 16, in __aenter__
    self.session = await start_session(self.service, self.browser, self.bind)
  File "C:\ProgramData\Anaconda3\lib\site-packages\arsenic\__init__.py", line 28, in start_session
    driver = await service.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\arsenic\services.py", line 107, in start
    return await subprocess_based_service(
  File "C:\ProgramData\Anaconda3\lib\site-packages\arsenic\services.py", line 34, in subprocess_based_service
    process = await impl.start_process(cmd, log_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\arsenic\subprocess.py", line 56, in start_process
    return await asyncio.create_subprocess_exec(
  File "C:\ProgramData\Anaconda3\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 385, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 881, in _start
    self._proc = windows_utils.Popen(
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by codingforentrepreneurs** [comment]
You’re using anaconda. Install Python from [python.org](https://python.org).
